apiVersion: v1
kind: Namespace
metadata:
  name: pet2cattle
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet2cattle
  namespace: pet2cattle
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: pet2cattle
      app.kubernetes.io/name: pet2cattle
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: pet2cattle
        app.kubernetes.io/name: pet2cattle
        component: app
    spec:
      containers:
      - env:
        - name: MINIO_BUCKET
          value: pet2cattle
        image: busybox
        name: pet2cattle
        command:
        - "sleep"
        - "24h"
